name: news_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  retrofit: ^4.9.2
  

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^10.2.1
  build_runner: ^2.10.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/placeholder.png
