name: news_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <3.8.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  dio: ^5.9.1
  flutter_bloc: ^9.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  retrofit: ^4.6.0
  shared_preferences: ^2.0.18

  # ðŸ”¥ Firebase (All Compatible Versions)
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  retrofit_generator: ^8.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/placeholder.png